### ISSUE TITLE
When using an external keyboard with its own smart card reader, disconnecting and reconnecting it causes BeIDCards to no longer find any cards

### ISSUE THREAD

**Issue by Glennovich** [Fedict/commons-eid#15]
Hello,

I'm working on an HP laptop which is docked into a docking station with an external Dell Smart Card Reader keyboard connected to it. When I insert an eID card and try to sign a PDF (via iText in Java), signing works. When I disconnect the keyboard however, BeIDCards seems to get stuck in a loop and it can no longer detect any cards.

In simple steps, reproducing the bug works like this:
1. start application with keyboard connected (card inserted or not does not matter)
2. try to sign a PDF (via a button in the application)
3. if card is not inserted, the system will ask for it
    if card is inserted, I get a screen to enter my PIN
4. disconnect the keyboard at this point (the only thing needed is that an instance of BeIDCards is actively running). normally the first error should start appearing in a loop. reconnecting the keyboard again will result in a different kind of error, but it will still run in a loop.

My laptop also has a built-in Alcor Micro USB Smart Card Reader. This second terminal is only detected upon inserting an eID card, thus the cardTerminalAttached and cardInserted events always fire together (cardTerminalDetached and cardRemoved as well). With this card reader, removal of the card does not pose an issue and I do not get the errorloop.

I've enabled logging in BeIDCards, signed one PDF (so BeIDCards is active), then disconnected the keyboard and reconnected it to reproduce this. Execution of the application is manually stopped from my IDE. You can find the console output of these actions in [eid_errorlog20190722.txt](https://github.com/Fedict/commons-eid/files/3418056/eid_errorlog20190722.txt) attached to this issue.

Thanks in advance for any help with this issue.

**Comment by Glennovich** [comment]
Follow-up: code to trigger the errors (digitally signing some text)
While the code is running (asking for eID card or PIN), disconnect the terminal and reconnect to trigger the exceptions.

import be.bosa.commons.eid.client.BeIDCard;
import be.bosa.commons.eid.client.BeIDCards;
import be.bosa.commons.eid.client.CancelledException;
import be.bosa.commons.eid.client.FileType;
import be.bosa.commons.eid.client.exception.BeIDException;
import be.bosa.commons.eid.client.impl.BeIDDigest;
import be.bosa.commons.eid.logger.TestLogger;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class SimulateBeIDCardsBug {

    private static BeIDCards beIDCards;
    private static BeIDCard beIDCard;

    public static void main(String[] args) throws InterruptedException {
        String textToSign = "Test";
        System.out.println("'" + textToSign + "' digitally signed becomes " + getDigitalSignatureFor(textToSign));


        //now try and sign a second piece of text
        textToSign = "Test nummer twee";
        System.out.println("'" + textToSign + "' digitally signed becomes " + getDigitalSignatureFor(textToSign));
    }

    private static byte[] getDigitalSignatureFor(String data) {
        beIDCards = new BeIDCards(new TestLogger());
        try {
            beIDCard = beIDCards.getOneBeIDCard();
            byte[] hashToSign = MessageDigest.getInstance("SHA-1").digest(data.getBytes());
            byte[] signature = beIDCard.sign(hashToSign, BeIDDigest.SHA_1, FileType.NonRepudiationCertificate, false);
            return signature;
        } catch (CancelledException ex) {
            System.out.println("Signing was canceled");
        } catch (NoSuchAlgorithmException ex) {
            ex.printStackTrace();
        } catch (BeIDException ex) {
            ex.printStackTrace();
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
        return null;
    }
}

**Comment by janvdbergh** [comment]
I still cannot reproduce the problem locally (macOS, Java 8 and Java 11). To me this looks like a bug in the smartcardio implementation of the specific Java version you are using.

**Comment by Glennovich** [comment]
I'm using Java 1.8.0_131 on Windows 7 Enterprise (Service pack 1) 64-bit.

**Comment by janvdbergh** [comment]
I'm currently using 1.8.0_151. Could you check if using the latest version
makes a difference?

**Comment by Glennovich** [comment]
I ran the code using jre 1.8.0_221 on a Windows 10 laptop without an external keyboard connected, using only an external cardterminal and the problem persists. Once I have unplugged the cardterminal and plugged it back in the same error messages started appearing.

I also installed jdk 11.0.4 and tried it again. In this case, the system tried reloading the smart card service, but I got an error about illegal reflective access in this case. After this error, I get the same sequence of errors as with the other jdks:

OS is [Windows 10]. Not Enabling PCSC library fix.
CardAndTerminalManager worker thread start requested.
Waiting for CardAndTerminalManager Terminals initialisation
CardAndTerminalManager worker thread started.
subsystem not initialized
eID Card Insertion Reported
CardAndTerminalManager now has terminals initialized
Waiting for CardAndTerminalManager Cards initialisation
eIDCardEventsInitialized
CardAndTerminalManager now has cards initialized
hasBeIDCards returns true
Getting CCID FEATURES using standard control command
GET_FEATURES over standard control command failed: transmitControlCommand() failed
Not risking PPDU Fallback strategy for CardTerminal [ACS CCID USB Reader 0] on this platform
---begin exclusive---
selecting key...
non-repudiation key detected, immediate PIN verify
---end exclusive---

(disconnected cardterminal at this point, whilst the enter PIN screen was shown)

Smart card service is on failure. Trying to reload the JDK SmartCard service.
**WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by be.bosa.commons.eid.client.impl.CardTerminalsProxy (file:/C:/Code/commons-eid-commons-eid-parent-1.0.5/commons-eid-client/target/classes/) to field sun.security.smartcardio.PCSCTerminals.contextId
WARNING: Please consider reporting this to the maintainers of be.bosa.commons.eid.client.impl.CardTerminalsProxy
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release**
Cannot wait for card terminal changes (no PCSC subsystem?): list() failed
no card readers connected?
cause: SCARD_E_NO_READERS_AVAILABLE
cause type: sun.security.smartcardio.PCSCException
closing eID card
eID Card Removal Reported
cleared
subsystem not initialized
Cannot enumerate card terminals [1] (No Card Readers Connected?): list() failed
no card readers connected?
cause: SCARD_E_NO_READERS_AVAILABLE
cause type: sun.security.smartcardio.PCSCException
cleared
subsystem not initialized

... (error is repeated until I reconnect cardterminal here)

eID Card Insertion Reported
Cannot wait for card terminal events [2] (No Card Readers Connected?): waitForChange() failed
no card readers connected?
cause: SCARD_E_NO_READERS_AVAILABLE
cause type: sun.security.smartcardio.PCSCException
closing eID card
eID Card Removal Reported
cleared
subsystem not initialized
eID Card Insertion Reported
Cannot wait for card terminal events [2] (No Card Readers Connected?): waitForChange() failed
no card readers connected?
cause: SCARD_E_NO_READERS_AVAILABLE
cause type: sun.security.smartcardio.PCSCException
closing eID card
eID Card Removal Reported
cleared

... (error is repeated until I sign the first string "Test" here)

Signing was canceled
'Test' digitally signed becomes null
OS is [Windows 10]. Not Enabling PCSC library fix.
CardAndTerminalManager worker thread start requested.
Waiting for CardAndTerminalManager Terminals initialisation
CardAndTerminalManager worker thread started.
subsystem not initialized
eID Card Insertion Reported
subsystem not initialized
eID Card Insertion Reported
Cannot wait for card terminal events [2] (No Card Readers Connected?): waitForChange() failed
no card readers connected?
cause: SCARD_E_NO_READERS_AVAILABLE
cause type: sun.security.smartcardio.PCSCException
closing eID card
eID Card Removal Reported
cleared
eIDCardEventsInitialized
CardAndTerminalManager now has terminals initialized
hasBeIDCards returns true
Getting CCID FEATURES using standard control command
Exception in thread "main" java.lang.IllegalStateException: Card has been disconnected
	at java.smartcardio/sun.security.smartcardio.CardImpl.checkState(CardImpl.java:109)
	at java.smartcardio/sun.security.smartcardio.CardImpl.transmitControlCommand(CardImpl.java:240)
	at be.bosa.commons.eid.client.impl.CCID.getFeaturesUsingControlChannel(CCID.java:140)
	at be.bosa.commons.eid.client.impl.CCID.<init>(CCID.java:119)
	at be.bosa.commons.eid.client.BeIDCard.getCCID(BeIDCard.java:1264)
	at be.bosa.commons.eid.client.BeIDCard.sign(BeIDCard.java:391)
	at be.bosa.commons.eid.examples.events.SimulateBeIDCardsBug.getDigitalSignatureFor(SimulateBeIDCardsBug.java:34)
	at be.bosa.commons.eid.examples.events.SimulateBeIDCardsBug.main(SimulateBeIDCardsBug.java:26)
subsystem not initialized
eID Card Insertion Reported
Cannot wait for card terminal events [2] (No Card Readers Connected?): waitForChange() failed
no card readers connected?
cause: SCARD_E_NO_READERS_AVAILABLE
cause type: sun.security.smartcardio.PCSCException
closing eID card
eID Card Removal Reported
cleared
subsystem not initialized
eID Card Insertion Reported
Cannot wait for card terminal events [2] (No Card Readers Connected?): waitForChange() failed
no card readers connected?
cause: SCARD_E_NO_READERS_AVAILABLE
cause type: sun.security.smartcardio.PCSCException
closing eID card
eID Card Removal Reported
cleared
subsystem not initialized

process finished with exit code 1
